---
# vars file for setup_dialout
telemetry:
  vrf: management
  destination_groups:
  - destination:
      encoding: gpb
      ip: 13.233.233.202
      port: '57000'
      protocol: grpc
    id: telegraf
  sensor_groups:
  - data_source: DME
    id: dme_bgp
  - id: dme_bgp
    path:
      depth: unbounded
      filter_condition: None
      name: sys/bgp/inst
      query_condition: query-target=subtree&target-subtree-class=bgpDom
  - id: dme_bgp
    path:
      depth: None
      filter_condition: None
      name: sys/bgp/inst/dom-default/af-[l2vpn-evpn]
      query_condition: None
  - id: dme_vlan
  - id: dme_vlan
    path:
      depth: '2'
      filter_condition: None
      name: sys/bd
      query_condition: None
  - data_source: DME
    id: dme_alarm
  - id: dme_alarm
    path:
      depth: unbounded
      filter_condition: None
      name: sys/alarms
      query_condition: None
  - data_source: YANG
    id: oc_system
  - id: oc_system
    path:
      depth: None
      filter_condition: None
      name: openconfig-platform:system/cpus/cpu/state/total
      query_condition: None
  - id: oc_system
    path:
      depth: None
      filter_condition: None
      name: openconfig-platform:system/processes/process/state
      query_condition: None
  - id: oc_system
    path:
      depth: None
      filter_condition: None
      name: openconfig-system:system/cpus/cpu/state/total/avg
      query_condition: None
  - id: oc_system
    path:
      depth: None
      filter_condition: None
      name: openconfig-system:system/memory/state
      query_condition: None
  - data_source: YANG
    id: oc_platform
  - id: oc_platform
    path:
      depth: None
      filter_condition: None
      name: openconfig-platform:components/component/power-supply/state
      query_condition: None
  - data_source: YANG
    id: oc_interface
  - id: oc_interface
    path:
      depth: None
      filter_condition: None
      name: openconfig-interfaces:interfaces/interface/state/counters
      query_condition: None
  - id: oc_interface
    path:
      depth: None
      filter_condition: None
      name: openconfig-interfaces:interfaces/interface[name=mgmt0]/subinterfaces/subinterface[index=0]/ipv4/addresses/address
      query_condition: None
  - data_source: YANG
    id: native_l3_vrf
  - id: native_l3_vrf
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/inst-items/Inst-list
      query_condition: None
  - data_source: YANG
    id: native_chassis
  - id: native_chassis
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/ch-items/psuslot-items
      query_condition: None
  - id: native_chassis
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/ch-items/supslot-items/SupCSlot-list/sup-items/sensor-items/Sensor-list
      query_condition: None
  - data_source: DME
    id: dme_system_event
  - id: dme_system_event
    path:
      depth: None
      filter_condition: None
      name: sys
      query_condition: None
  - id: dme_system_event
    path:
      depth: None
      filter_condition: None
      name: sys/showversion
      query_condition: None
  - data_source: YANG
    id: native_mac_table
  - id: native_mac_table
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/mac-items/table-items/vlan-items/MacAddressEntry-list
      query_condition: None
  - data_source: DME
    id: dme_system_sample
  - id: dme_system_sample
    path:
      depth: None
      filter_condition: None
      name: sys/procsys/syscpusummary/syscpuhistory-last60seconds
      query_condition: None
  - id: dme_system_sample
    path:
      depth: None
      filter_condition: None
      name: sys/procsys/sysmem/sysmemusage
      query_condition: None
  - data_source: DME
    id: dme_interface_event
  - id: dme_interface_event
    path:
      depth: unbounded
      filter_condition: None
      name: sys/intf
      query_condition: query-target=subtree&target-subtree-class=ethpmPhysIf
  - data_source: YANG
    id: native_int_counters
  - id: native_int_counters
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfIn-items
      query_condition: None
  - id: native_int_counters
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfOut-items
      query_condition: None
  - data_source: YANG
    id: native_route_number
  - id: native_route_number
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/u6rib-items/table6-items/Table6-list/routeCount
      query_condition: None
  - id: native_route_number
    path:
      depth: None
      filter_condition: None
      name: Cisco-NX-OS-device:System/urib-items/table4-items/Table4-list/routeCount
      query_condition: None
  subscriptions:
  - destination_group: telegraf
    id: '1'
  - id: '1'
    sensor_group:
      id: dme_bgp
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: dme_vlan
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: dme_alarm
      sample_interval: '15000'
  - id: '1'
    sensor_group:
      id: oc_system
      sample_interval: '10000'
  - id: '1'
    sensor_group:
      id: oc_platform
      sample_interval: '10000'
  - id: '1'
    sensor_group:
      id: oc_interface
      sample_interval: '10000'
  - id: '1'
    sensor_group:
      id: native_l3_vrf
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: native_chassis
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: dme_system_event
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: native_mac_table
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: dme_system_sample
      sample_interval: '10000'
  - id: '1'
    sensor_group:
      id: dme_interface_event
      sample_interval: '30000'
  - id: '1'
    sensor_group:
      id: native_int_counters
      sample_interval: '10000'
  - id: '1'
    sensor_group:
      id: native_route_number
      sample_interval: '30000'
  - destination_group: telegraf
    id: '2'
  - id: '2'
    sensor_group:
      id: dme_bgp
      sample_interval: '0'
  - id: '2'
    sensor_group:
      id: dme_vlan
      sample_interval: '0'
  - id: '2'
    sensor_group:
      id: native_l3_vrf
      sample_interval: '0'
  - id: '2'
    sensor_group:
      id: dme_system_event
      sample_interval: '0'
  - id: '2'
    sensor_group:
      id: dme_interface_event
      sample_interval: '0'
  - id: '2'
    sensor_group:
      id: native_route_number
      sample_interval: '0'