---
# vars file for setup_collector
package_path:
  destination: /home/ubuntu
  influxdb: https://dl.influxdata.com/influxdb/releases/influxdb2-2.4.0-amd64.deb
  influx_client: https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.4.0-linux-amd64.tar.gz
  telegraf: https://dl.influxdata.com/telegraf/releases/telegraf_1.21.4-1_amd64.deb
  grafana: https://dl.grafana.com/enterprise/release/grafana-enterprise_9.1.6_amd64.deb

telegraf:
  config: files/telegraf/telegraf.conf.j2
  dialin_config: files/telegraf/gnmi.conf.j2
  certificates: /home/ubuntu/certs/

influxdb:
  org: Ansible
  username: ansible
  password: ansible123
  token: MySecretToken
  dialout_bucket: nxos_dialout
  dialin_bucket: nxos_gnmi

influx_client:
  name: influxdb2-client-2.4.0-linux-amd64
  setup: "influx setup --org {{ influxdb.org }} --bucket {{ influxdb.dialout_bucket }} --username {{ influxdb.username }} --password {{ influxdb.password }} --token {{ influxdb.token }} --retention 2h --force"
  dialin_bucket: "influx bucket create -n {{ influxdb.dialin_bucket }} -r 2h"

grafana:
  org_name: Ansible
  org_role: Admin
  config: files/grafana/grafana.ini.j2
  datasources: files/grafana/datasources/datasources.yaml.j2
  dashboards:
    definitions: 
      - files/grafana/dashboards/dashboard_vxlan_dialout.json
      - files/grafana/dashboards/dashboard_vxlan_dialin.json
    config: files/grafana/dashboards/dashboards.yaml

telemetry:
  transport: "grpc"
  service_address: ":57000"

dialout:
  target: 
    ip: 192.168.1.101

dialin:
  target:
    ip: 192.168.1.100
    port: 50051
    username: admin
    password: admin