---
# tasks file for configuring dialout
- name: Copy Telegraf dial out certificate to the device
  cisco.nxos.nxos_file_copy:
    local_file: "{{ dialout.certificate }}"
    remote_file: telegraf.crt

