---
# tasks file for configuring dialout
- name: Copy Telegraf dial out certificate to the device
  cisco.nxos.nxos_file_copy:
    local_file: "{{ dialout.certificate }}"
    remote_file: telegraf.crt

- name: Running configure
  cisco.nxos.nxos_telemetry:
    config: "{{ dialout.telemetry }}"
    state: merged

- name: Validate Telemetry Transport
  ansible.builtin.include_tasks: validate_dialout.yaml
  when: validate | d(False)
