---
# tasks file for setup_nxos
- debug:
    msg: "Start setting up NX-OS telemetry configuration"

- name: Override variables (if specified)
  ansible.builtin.include_vars:
    file: "{{ nxos_setup_data }}"
  when: nxos_setup_data is defined

- name: Turn on feature SCP and gRPC
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop:
    - scp-server
    - grpc

- name: Configure Dial-Out Telemetry
  ansible.builtin.include_tasks: configure_dialout.yaml

- name: Configure Dial-In Telemetry
  ansible.builtin.include_tasks: configure_dialin.yaml
