---
# tasks file for validating telemetry transport

- name: Allow the dialout connection to be established
  ansible.builtin.pause:
    seconds: 10

- name: Fetch telemetry transport information
  cisco.nxos.nxos_command:
    commands: show telemetry transport
  register: result

- name: Assert that all collectors are connected
  ansible.builtin.assert:
    that: "'Transmit Error' not in result.stdout[0]"
