---
# vars file for setup_nxos
dialin:
  certificate: /etc/telegraf/cert/gnmi.pfx
  passphrase: cisco123

dialout:
  collector_ip: 192.168.55.1
  certificate: /etc/telegraf/cert/telegraf.crt
  telemetry:
    certificate:
      hostname: telegraf
      key: /bootflash/telegraf.crt
    destination_groups:
      - destination:
          encoding: gpb
          ip: 10.122.197.147
          port: '57000'
          protocol: grpc
        id: telegraf
    sensor_groups:
      - data_source: YANG
        id: evpn
      - id: evpn
        path:
          name: openconfig-network-instance:/network-instances/network-instance/fdb/l2rib/mac-table/entries/entry
      - id: evpn
        path:
          name: openconfig-network-instance:/network-instances/network-instance/fdb/mac-table/entries
      - id: evpn
        path:
          name: openconfig-network-instance:/network-instances/network-instance/protocols/protocol/bgp/rib/afi-safis/afi-safi/l2vpn-evpn/loc-rib/routes
      - id: evpn
        path:
          name: openconfig-network-instance:/network-instances/network-instance/protocols/protocol/bgp/rib/afi-safis/afi-safi/l2vpn-evpn/loc-rib/routes/route-distinguisher/type-five-ip-prefix/type-five-route/state
      - id: evpn
        path:
          name: openconfig-network-instance:/network-instances/network-instance/protocols/protocol/bgp/rib/afi-safis/afi-safi/l2vpn-evpn/loc-rib/routes/route-distinguisher/type-two-mac-ip-advertisement/type-two-route/state
      - data_source: DME
        id: dme_bgp
      - id: dme_bgp
        path:
          depth: unbounded
          name: sys/bgp/inst
          query_condition: query-target=subtree&target-subtree-class=bgpDom
      - id: dme_bgp
        path:
          name: sys/bgp/inst/dom-default/af-[l2vpn-evpn]
      - id: dme_vlan
      - id: dme_vlan
        path:
          depth: '2'
          name: sys/bd
      - data_source: DME
        id: dme_alarm
      - id: dme_alarm
        path:
          depth: unbounded
          name: sys/alarms
      - data_source: YANG
        id: oc_system
      - id: oc_system
        path:
          name: openconfig-platform:system/cpus/cpu/state/total
      - id: oc_system
        path:
          name: openconfig-platform:system/processes/process/state
      - id: oc_system
        path:
          name: openconfig-system:system/cpus/cpu/state/total/avg
      - id: oc_system
        path:
          name: openconfig-system:system/memory/state
      - data_source: YANG
        id: oc_platform
      - id: oc_platform
        path:
          name: openconfig-platform:components/component/power-supply/state
      - data_source: YANG
        id: oc_interface
      - id: oc_interface
        path:
          name: openconfig-interfaces:interfaces/interface/state/counters
      - id: oc_interface
        path:
          name: openconfig-interfaces:interfaces/interface[name=mgmt0]/subinterfaces/subinterface[index=0]/ipv4/addresses/address
      - data_source: YANG
        id: native_l3_vrf
      - id: native_l3_vrf
        path:
          name: Cisco-NX-OS-device:System/inst-items/Inst-list
      - data_source: YANG
        id: native_chassis
      - id: native_chassis
        path:
          name: Cisco-NX-OS-device:System/ch-items/psuslot-items
      - id: native_chassis
        path:
          name: Cisco-NX-OS-device:System/ch-items/supslot-items/SupCSlot-list/sup-items/sensor-items/Sensor-list
      - data_source: DME
        id: dme_system_event
      - id: dme_system_event
        path:
          name: sys
      - id: dme_system_event
        path:
          name: sys/showversion
      - data_source: YANG
        id: native_mac_table
      - id: native_mac_table
        path:
          name: Cisco-NX-OS-device:System/mac-items/table-items/vlan-items/MacAddressEntry-list
      - data_source: DME
        id: dme_system_sample
      - id: dme_system_sample
        path:
          name: sys/procsys/syscpusummary/syscpuhistory-last60seconds
      - id: dme_system_sample
        path:
          name: sys/procsys/sysmem/sysmemusage
      - data_source: DME
        id: dme_interface_event
      - id: dme_interface_event
        path:
          depth: unbounded
          name: sys/intf
          query_condition: query-target=subtree&target-subtree-class=ethpmPhysIf
      - data_source: YANG
        id: native_int_counters
      - id: native_int_counters
        path:
          name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfIn-items
      - id: native_int_counters
        path:
          name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfOut-items
      - data_source: YANG
        id: native_route_number
      - id: native_route_number
        path:
          name: Cisco-NX-OS-device:System/u6rib-items/table6-items/Table6-list/routeCount
      - id: native_route_number
        path:
          name: Cisco-NX-OS-device:System/urib-items/table4-items/Table4-list/routeCount
    subscriptions:
      - destination_group: telegraf
        id: '1'
      - id: '1'
        sensor_group:
          id: dme_bgp
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: dme_vlan
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: dme_alarm
          sample_interval: '15000'
      - id: '1'
        sensor_group:
          id: oc_system
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: oc_platform
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: oc_interface
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: native_l3_vrf
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: native_chassis
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: dme_system_event
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: native_mac_table
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: dme_system_sample
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: dme_interface_event
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: native_int_counters
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: native_route_number
          sample_interval: '30000'
      - destination_group: telegraf
        id: '2'
      - id: '2'
        sensor_group:
          id: dme_bgp
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: dme_vlan
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: native_l3_vrf
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: dme_system_event
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: dme_interface_event
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: native_route_number
          sample_interval: '0'
      - destination_group: telegraf
        id: '3'
      - id: '3'
        sensor_group:
          id: evpn
          sample_interval: '1000'
    vrf: management
