---
# vars file for setup_nxos
dialin:
  certificate: /home/nchakrab/ansible-collections/certs/gnmi.pfx
  passphrase: cisco123

dialout:
  certificate: /home/nchakrab/ansible-collections/certs/telegraf.crt
  telemetry:
    vrf: management
    certificate:
      key: /bootflash/telegraf.crt
      hostname: telegraf
    destination_groups:
      - destination:
          encoding: gpb
          ip: "{{ collector_ip }}"
          port: '57000'
          protocol: grpc
        id: '1'
    sensor_groups:
      - data_source: DME
        id: '0'
      - id: '0'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/bgp/inst
          query_condition: query-target=subtree&target-subtree-class=bgpDom
      - id: '0'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/bgp/inst/dom-default/af-[l2vpn-evpn]
          query_condition: None
      - id: '1'
      - id: '1'
        path:
          depth: '2'
          filter_condition: None
          name: sys/bd
          query_condition: None
      - data_source: DME
        id: '2'
      - id: '2'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/alarms
          query_condition: None
      - data_source: YANG
        id: '3'
      - id: '3'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-platform:system/cpus/cpu/state/total
          query_condition: None
      - id: '3'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-platform:system/processes/process/state
          query_condition: None
      - id: '3'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-system:system/cpus/cpu/state/total/avg
          query_condition: None
      - id: '3'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-system:system/memory/state
          query_condition: None
      - data_source: YANG
        id: '4'
      - id: '4'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-platform:components/component/power-supply/state
          query_condition: None
      - data_source: YANG
        id: '5'
      - id: '5'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-interfaces:interfaces/interface/state/counters
          query_condition: None
      - id: '5'
        path:
          depth: unbounded
          filter_condition: None
          name: openconfig-interfaces:interfaces/interface[name=mgmt0]/subinterfaces/subinterface[index=0]/ipv4/addresses/address
          query_condition: None
      - data_source: YANG
        id: '6'
      - id: '6'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/inst-items/Inst-list
          query_condition: None
      - data_source: YANG
        id: '7'
      - id: '7'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/ch-items/psuslot-items
          query_condition: None
      - id: '7'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/ch-items/supslot-items/SupCSlot-list/sup-items/sensor-items/Sensor-list
          query_condition: None
      - data_source: DME
        id: '8'
      - id: '8'
        path:
          depth: unbounded
          filter_condition: None
          name: sys
          query_condition: None
      - id: '8'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/showversion
          query_condition: None
      - data_source: YANG
        id: '9'
      - id: '9'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/mac-items/table-items/vlan-items/MacAddressEntry-list
          query_condition: None
      - data_source: DME
        id: '10'
      - id: '10'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/procsys/syscpusummary/syscpuhistory-last60seconds
          query_condition: None
      - id: '10'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/procsys/sysmem/sysmemusage
          query_condition: None
      - data_source: DME
        id: '11'
      - id: '11'
        path:
          depth: unbounded
          filter_condition: None
          name: sys/intf
          query_condition: query-target=subtree&target-subtree-class=ethpmPhysIf
      - data_source: YANG
        id: '12'
      - id: '12'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfIn-items
          query_condition: None
      - id: '12'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/intf-items/phys-items/PhysIf-list/dbgIfOut-items
          query_condition: None
      - data_source: YANG
        id: '13'
      - id: '13'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/u6rib-items/table6-items/Table6-list/routeCount
          query_condition: None
      - id: '13'
        path:
          depth: unbounded
          filter_condition: None
          name: Cisco-NX-OS-device:System/urib-items/table4-items/Table4-list/routeCount
          query_condition: None
    subscriptions:
      - destination_group: 1
        id: '1'
      - id: '1'
        sensor_group:
          id: '0'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '1'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '2'
          sample_interval: '15000'
      - id: '1'
        sensor_group:
          id: '3'
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: '4'
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: '5'
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: '6'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '7'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '8'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '9'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '10'
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: '11'
          sample_interval: '30000'
      - id: '1'
        sensor_group:
          id: '12'
          sample_interval: '10000'
      - id: '1'
        sensor_group:
          id: '13'
          sample_interval: '30000'
      - destination_group: 1
        id: '2'
      - id: '2'
        sensor_group:
          id: '0'
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: '1'
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: '6'
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: '8'
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: '11'
          sample_interval: '0'
      - id: '2'
        sensor_group:
          id: '13'
          sample_interval: '0'
