---
- name: "Fetch Telegraf package"
  ansible.builtin.get_url:
    url: "{{ package_path.telegraf }}"
    dest: "{{ package_path.destination }}"
  environment:
    http_proxy: "{{ proxy.http | default(None) }}"
    https_proxy: "{{ proxy.https | default(None) }}"

- name: "Install Telegraf"
  ansible.builtin.apt:
    deb: "{{ package_path.destination }}/{{ package_path.telegraf.split('/')[-1] }}"
  register: result
  ignore_errors: true


- name: "Copy Telegraf authentication certificates"
  ansible.builtin.copy:
    src: "{{ telegraf.certificates }}"
    dest: /etc/telegraf/cert/
  notify:
    - restart_telegraf
    - restart_influxdb

- name: "Copy Telegraf configuration file"
  ansible.builtin.template:
    src: "{{ telegraf.config }}"
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart_telegraf
    - restart_influxdb

- name: "Copy Telegraf dial-in configuration file"
  ansible.builtin.template:
    src: "{{ telegraf.dialin_config }}"
    dest: /etc/telegraf/telegraf.d/gnmi.conf
  notify:
    - restart_telegraf
    - restart_influxdb

- name: "Start telegraf service"
  ansible.builtin.service:
    name: telegraf
    state: started
