---
- name: Fetch Telegraf package
  ansible.builtin.get_url:
    url: "{{ package_path.telegraf }}"
    dest: "{{ package_path.destination }}"

- name: Install Telegraf
  ansible.builtin.apt:
    deb: "{{ package_path.destination }}/{{ package_path.telegraf.split('/')[-1] }}"
  register: result

- name: Copy Telegraf configuration file
  ansible.builtin.template:
    src: "{{ telegraf.config }}"
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart_telegraf
    - restart_influxdb

- name: Start telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
