---
- name: Install Telegraf
  ansible.builtin.package:
    name: telegraf
    state: present

- name: Copy Telegraf configuration file
  ansible.builtin.template:
    src: files/telegraf/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart_telegraf
    - restart_influxdb

- name: Start telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
