---
- name: Setup Grafana
  hosts: collector
  gather_facts: yes
  tasks:
    - name: Fetch grafana
      ansible.builtin.get_url:
        url: "{{ package_path.grafana }}"
        dest: "{{ package_path.destination }}"

    - name: Install grafana
      ansible.builtin.apt:
        deb: "{{ package_path.destination }}/{{ package_path.grafana.split('/')[-1] }}"

    - name: Copy grafana configuration file
      ansible.builtin.template:
        src: "{{ grafana.config }}"
        dest: /etc/grafana/grafana.ini
      notify: restart_grafana

    - name: Copy grafana datasources
      ansible.builtin.template:
        src: "{{ grafana.datasources }}"
        dest: /etc/grafana/provisioning/datasources/datasources.yaml
      notify: restart_grafana

    - name: Copy grafana dashboard for VXLAN dialout
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/grafana/provisioning/dashboards/{{ item.split('/')[-1] }}"
      loop: "{{ grafana.dashboards.definitions }}"
      notify: restart_grafana

    - name: Copy grafana dashboard YAML file
      ansible.builtin.template:
        src: "{{ grafana.dashboards.config }}"
        dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
      notify: restart_grafana

    - name: Start grafana service
      ansible.builtin.service:
        name: grafana-server
        state: started

  handlers:
    - name: restart_grafana
      ansible.builtin.service:
        name: grafana-server
        state: restarted
